spring:
  application:
    name: karyawancrudapp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 122
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
